name: admin_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.4+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  factoryflow_core:
    path: ../../packages/core
  http: ^1.1.0
  package_info_plus: ^8.1.1
  image_picker: ^1.2.1
  device_info_plus: ^12.3.0
  url_launcher: ^6.3.1
  excel: ^4.0.5
  share_plus: 10.1.1
  fl_chart: ^0.70.2
  file_picker: ^10.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  msix: ^3.16.7

flutter:
  uses-material-design: true