name: admin_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  factoryflow_core:
    path: ../../packages/core
  http: ^1.1.0
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  msix: ^3.16.7

flutter:
  uses-material-design: true
