name: admin_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  factoryflow_core:
    path: ../../packages/core
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  supabase_flutter: ^2.10.3
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  http: ^1.2.2
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  device_info_plus: ^12.3.0
  image_picker: ^1.2.1
  package_info_plus: ^8.1.1
  excel: ^4.0.5
  share_plus: ^10.1.1
  fl_chart: ^0.70.2
  file_picker: ^10.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  msix: ^3.16.7

flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - assets/images/