name: factoryflow_core
description: Core package for FactoryFlow containing shared models, services, and utils.
version: 1.0.1
publish_to: 'none'

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.3
  intl: ^0.20.2
  geolocator: ^14.0.2
  shared_preferences: ^2.5.4
  http: ^1.2.2
  uuid: ^4.5.1
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  device_info_plus: ^12.3.0
  file_picker: ^10.3.8
  workmanager: ^0.9.0+3
  flutter_local_notifications: ^18.0.1
  animations: ^2.1.1
  flutter_animate: ^4.5.2
  local_auth: ^2.3.0
  permission_handler: ^12.0.1
  package_info_plus: ^8.1.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
